export const allProductsDropDownArray = [
  {
    id: crypto.randomUUID(),
    category: {
      title: "Electronics",
      subItems: [
        {
          subtitle: "Mobiles",
          items: [
            "Mi",
            "Realme",
            "Samsung",
            "Infinix",
            "OPPO",
            "Apple",
            "Vivo",
            "Honor",
            "Asus",
            "Poco X2",
            "realme Narzo 10",
            "Infinix Hot 9",
            "IQOO 3",
            "iPhone SE",
            "Motorola razr",
            "realme Narzo 10A",
            "Motorola g8 power lite",
          ],
        },
        {
          subtitle: "Mobile Accessories",
          items: [
            "Mobile Cases",
            "Headphones & Headsets",
            "Power Banks",
            "Screenguards",
            "Memory Cards",
            "Smart Headphones",
            "Mobile Cables",
            "Mobile Chargers",
            "Mobile Holders",
          ],
        },
        {
          subtitle: "Smart Wearable Tech",
          items: ["Smart Watches", "Smart Glasses (VR)", "Smart Bands"],
        },
        {
          subtitle: "Health Care Appliances",
          items: ["Bp Monitors", "Weighing Scale"],
        },

        {
          subtitle: "Laptops",
          items: ["Gaming Laptops"],
        },
        {
          subtitle: "Desktop PCs",
          items: [],
        },
        {
          subtitle: "Gaming & Accessories",
          items: [],
        },
        {
          subtitle: "Computer Accessories",
          items: [
            "External Hard Disks",
            "Pendrives",
            "Laptop Skins & Decals",
            "Laptop Bags",
            "Mouse",
          ],
        },
        {
          subtitle: "Computer Peripherals",
          items: ["Printers & Ink Cartridges", "Monitors"],
        },
        {
          subtitle: "Tablets",
          items: ["Apple iPads"],
        },

        {
          subtitle: "Speakers",
          items: [
            "Home Audio Speakers",
            "Home Theatres",
            "Soundbars",
            "Bluetooth Speakers",
            "DTH Set Top Box",
          ],
        },
        {
          subtitle: "Smart Home Automation",
          items: ["Google Nest"],
        },
        {
          subtitle: "Camera",
          items: [
            "DSLR & Mirrorless",
            "Compact & Bridge Cameras",
            "Sports & Action",
          ],
        },
        {
          subtitle: "Camera Accessories",
          items: ["Lens", "Tripods"],
        },
        {
          subtitle: "Network Components",
          items: ["Routers"],
        },
        {
          subtitle: "Featured",
          items: [
            "Google Assistant Store",
            "Laptops on Buyback Guarantee",
            "Flipkart SmartBuy",
            "Li-Polymer Power Banks",
            "Sony PS4 Pro & Slim",
            "Apple Products",
            "Microsoft Store",
            "Lenovo Phab Series",
            "JBL Speakers",
            "Smartphones On Buyback Guarantee",
            "Philips",
            "Dr. Morepen",
            "Complete Mobile Protection",
            "Mobiles No Cost EMI",
            "Huawei Watch Gt 2e Smart Watch",
          ],
        },
      ],
    },
  },
  {
    id: crypto.randomUUID(),
    category: {
      title: "TVs & Appliances",
      subItems: [
        {
          subtitle: "Television",
          items: [],
        },
        {
          subtitle: "New Launches",
          items: [],
        },
        {
          subtitle: "Smart & Ultra HD",
          items: [],
        },
        {
          subtitle: "Top Brands",
          items: [
            "Mi",
            "Vu",
            "Thomson",
            "Samsung",
            "iFFALCON by TCL",
            "Nokia",
            "LG",
            "realme",
            "Motorola",
          ],
        },
        {
          subtitle: "Shop by Screen Size",
          items: ["24 & below", "28 - 32", "39 - 43", "48 - 55", "60 & above"],
        },
        {
          subtitle: "Washing Machine",
          items: [
            "Fully Automatic Front Load",
            "Semi Automatic Top Load",
            "Fully Automatic Top Load",
          ],
        },
        {
          subtitle: "Air Conditioners",
          items: ["Inverter AC", "Split ACs", "Window ACs"],
        },
        {
          subtitle: "Shop By Brand",
          items: ["LG", "Hitachi", "Carrier"],
        },
        {
          subtitle: "Refrigerators",
          items: [
            "Single Door",
            "Double Door",
            "Triple door",
            "Side by Side",
            "Convertible",
          ],
        },
        {
          subtitle: "Kitchen Appliances",
          items: [
            "Microwave Ovens",
            "Oven Toaster Grills (OTG)",
            "Juicer/Mixer/Grinder",
            "Electric Kettle",
            "Induction Cooktops",
            "Chimneys",
            "Hand Blenders",
            "Sandwich Makers",
            "Pop Up Toasters",
            "Electric Cookers",
            "Wet Grinders",
            "Food Processors",
            "Coffee Makers",
            "Dishwashers",
          ],
        },
        {
          subtitle: "Healthy Living Appliances",
          items: [],
        },
        {
          subtitle: "Small Home Appliances",
          items: [
            "Irons",
            "Water Purifiers",
            "Fans",
            "Air Coolers",
            "Inverters",
            "Vacuum Cleaners",
            "Sewing Machines",
            "Voltage Stabilizers",
            "Water Geysers",
            "Immersion Rods",
          ],
        },
        {
          subtitle: "Top Brands",
          items: [
            "Livpure",
            "Philips",
            "Bajaj",
            "IFB",
            "Eureka Forbes",
            "Kaff",
          ],
        },
        {
          subtitle: "Buying Guides",
          items: [
            "Televisions",
            "Washing Machines",
            "Refrigerators",
            "Air Conditioners",
            "Water Purifiers",
            "Air Purifiers",
            "Chimneys",
            "Water Geysers",
          ],
        },
        {
          subtitle: "New Launches",
          items: [
            "Coocaa Smart TVs",
            "Nokia (55) 4K Android TV",
            "Mi (32) 4A Pro Android TV",
            "MarQ (43) FHD Smart TV",
            "LG Refrigerators",
            "Thomson (40) 4K Smart TV",
            "Whirlpool Refrigerators",
            "Kodak (22) | (32) LED TVs",
          ],
        },
      ],
    },
  },
  {
    id: crypto.randomUUID(),
    categoryItems: {
      title: "Mens",
      subItems: [
        {
          subtitle: "Footwear",
          items: [
            "Sports Shoes",
            "Casual Shoes",
            "Formal Shoes",
            "Sandals & Floaters",
            "Flip- Flops",
            "Loafers",
            "Boots",
            "Running Shoes",
            "Sneakers",
          ],
        },
        {
          subtitle: "Men's Grooming",
          items: [
            "Deodorants",
            "Perfumes",
            "Beard Care & Grooming",
            "Shaving & Aftershave",
            "Sexual Wellness",
          ],
        },
        {
          subtitle: "Clothing",
          items: [
            "Top wear",
            "T-Shirts",
            "Formal Shirts",
            "Casual Shirts",
            "Bottom wear",
            "Jeans",
            "Casual Trousers",
            "Formal Trousers",
            "Track pants",
            "Shorts",
            "Cargos",
            "Three Fourths",
            "Suits, Blazers & Waistcoats",
            "Ties, Socks, Caps & More",
            "Fabrics",
          ],
        },
        {
          subtitle: "Winter Wear",
          items: ["Sweatshirts", "Jackets", "Sweater", "Tracksuits"],
        },
        {
          subtitle: "Ethnic Wear",
          items: [
            "Kurta",
            "Ethnic Sets",
            "Sherwanis",
            "Ethnic Pyjama",
            "Dhoti",
            "Lungi",
          ],
        },
        {
          subtitle: "Innerwear & Loungewear",
          items: [
            "Briefs & Trunks",
            "Vests",
            "Boxers",
            "Pyjamas and Lounge Pants",
            "Thermals",
            "Night Suits",
            "Raincoats & Windcheaters",
          ],
        },
        {
          subtitle: "Watches",
          items: ["Fastrack", "Casio", "Titan", "Fossil", "Sonata"],
        },
        {
          subtitle: "Accessories",
          items: [
            "Backpacks",
            "Wallets",
            "Belts",
            "Sunglasses",
            "Luggage & Travel",
            "Frames",
            "Jewellery",
          ],
        },
        {
          subtitle: "Sports & Fitness",
          items: ["Smart Watches", "Smart Bands"],
        },
        {
          subtitle: "Personal Care Appliances",
          items: ["Trimmers", "Shavers", "Grooming Kits"],
        },
        {
          subtitle: "Featured",
          items: [
            "Watches Store",
            "Footwear Club",
            "Bags & Wallet",
            "T-Shirt Store",
            "Adidas",
            "Beardo",
            "Reebok",
            "Skechers",
            "Nike",
          ],
        },
      ],
    },
  },

  {
    id: crypto.randomUUID(),
    category: {
      title: "Women",
      subItems: [
        {
          subtitle: "Clothing",
          items: [],
        },
        {
          subtitle: "Western & Maternity Wear",
          items: [
            "Topwear",
            "Dresses",
            "Jeans",
            "Shorts",
            "Skirts",
            "Jeggings & Tights",
            "Trousers & Capris",
          ],
        },
        {
          subtitle: "Lingerie & Sleepwear",
          items: [
            "Bras",
            "Panties",
            "Lingerie Sets",
            "Night Dresses & Nighties",
            "Shapewear",
            "Camisoles & Slips",
          ],
        },
        {
          subtitle: "Swim & Beachwear",
          items: [],
        },
        {
          subtitle: "Party Dresses",
          items: [],
        },
        {
          subtitle: "Sports Wear",
          items: [],
        },
        {
          subtitle: "Winter Wear",
          items: [],
        },
        {
          subtitle: "Ethnic Wear",
          items: [
            "Sarees",
            "Kurtas & Kurtis",
            "Dress Material",
            "Lehenga Choli",
            "Blouse",
            "Kurta Sets & Salwar Suits",
            "Gowns",
            "Dupattas",
          ],
        },
        {
          subtitle: "Ethnic Bottoms",
          items: [
            "Leggings & Churidars",
            "Palazzos",
            "Shararas",
            "Salwars & Patiala",
            "Dhoti Pants",
            "Ethnic Trousers",
            "Saree Shapewear & Petticoats",
          ],
        },
        {
          subtitle: "Footwear",
          items: [],
        },
        {
          subtitle: "Sandals",
          items: ["Flats", "Heels", "Wedges"],
        },
        {
          subtitle: "Shoes",
          items: ["Sports Shoes", "Casual Shoes", "Boots"],
        },
        {
          subtitle: "Ballerinas",
          items: [],
        },
        {
          subtitle: "Slippers & Flip-Flop's",
          items: [],
        },
        {
          subtitle: "Watches",
          items: [],
        },
        {
          subtitle: "Smart Watches",
          items: [],
        },
        {
          subtitle: "Personal Care Appliances",
          items: ["Hair Straightners", "Hair Dryers", "Epilators"],
        },
        {
          subtitle: "Beauty & Grooming",
          items: [
            "Make Up",
            "Skin Care",
            "Hair Care",
            "Bath & Spa",
            "Deodorants & Perfumes",
          ],
        },
        {
          subtitle: "Jewellery",
          items: [
            "Artificial Jewellery",
            "Silver Jewellery",
            "Precious Jewellery",
            "Coins and Bars",
          ],
        },
        {
          subtitle: "Accessories",
          items: [
            "Handbags",
            "Shoulder Bags",
            "Totes",
            "Sling bags",
            "Clutches",
            "Wallets & Belts",
            "Luggage & Travel",
            "Sunglasses",
            "Frames",
          ],
        },
        {
          subtitle: "Featured",
          items: [
            "Forever 21",
            "Accessorize",
            "W",
            "Pantaloons",
            "Chemistry",
            "Lakme",
            "Nivea",
            "Catwalk",
            "Titan-Raga",
            "Fastrack",
            "Divastri",
            "Rare Roots",
            "Anmi",
            "Coins & Bars",
            "Crocs",
          ],
        },
        {
          subtitle: "Trending today!",
          items: [
            "Ruffles & Frills",
            "Pastel Kurtas & Kurtis",
            "Designer Net Sarees",
          ],
        },
      ],
    },
  },
  {
    id: crypto.randomUUID(),
    categoryItems: {
      title: "Baby & Kids",
      subItems: [
        {
          subtitle: "Boys' Clothing",
          items: ["T-Shirts", "Ethnic Wear", "Shorts", "Shirts", "Innerwear"],
        },
        {
          subtitle: "Girls' Clothing",
          items: [
            "Dresses & Skirts",
            "Ethnic Wear",
            "T-shirts & Tops",
            "Innerwear",
          ],
        },
        {
          subtitle: "Baby Boys' Clothing",
          items: ["Combos Sets", "T-Shirts", "Innerwear"],
        },
        {
          subtitle: "Baby Girls' Clothing",
          items: ["Combos Sets", "Dresses & Gowns", "Innerwear"],
        },
        {
          subtitle: "Kids' Footwear",
          items: [
            "Boys' Footwear",
            "Sandals",
            "Sport Shoes",
            "Girls' Footwear",
            "Flats & Bellies",
            "Sport Shoes",
            "Infant Footwear",
            "Character Shoes",
          ],
        },
        {
          subtitle: "Accessories",
          items: ["Kids' Watches", "Kids' Sunglasses"],
        },
        {
          subtitle: "Kids' Winter Wear",
          items: [
            "Boys' Winter Wear",
            "Boys' Sweatshirts",
            "Boys' Jacket",
            "Girls' Winter Wear",
            "Girls' Sweatshirts",
            "Girls' Jackets",
            "Infant Winter Wear",
            "Thermals",
          ],
        },
        {
          subtitle: "Toys",
          items: [
            "Remote Control Toys",
            "Educational Toys",
            "Soft Toys",
            "Cars & Die-cast Vehicles",
            "Outdoor Toys",
            "Action Figures",
            "Board Games",
            "Musical Toys",
            "Dolls & Doll Houses",
            "Puzzles",
            "S.T.E.M Toys",
            "Helicopter & Drones",
            "Toy Guns",
          ],
        },
        {
          subtitle: "Party Supplies",
          items: ["Party Supplies"],
        },
        {
          subtitle: "School Supplies",
          items: ["School Bags", "School Combo Sets", "Lunch Box"],
        },
        {
          subtitle: "Baby Care",
          items: [
            "Diapers",
            "Wipes",
            "Diapering & Potty Training",
            "Baby Bath, Hair & Skin Care",
            "Baby Grooming",
            "Baby Bathing Accessories",
            "Baby Gift Sets & Combo",
            "Baby Oral Care",
            "Nursing & Breast Feeding",
            "Baby Food",
            "Baby Feeding Bottle & Accessories",
            "Baby Feeding Utensils & Accessories",
            "Baby Bedding",
            "Baby Gear",
            "Baby Medical & Health Care",
            "Baby Proofing & Safety",
            "Baby Cleaners & Detergents",
          ],
        },
        {
          subtitle: "Featured Brands",
          items: [
            "Miss & Chief",
            "Barbie",
            "Disney",
            "United Colors of Benetton",
            "The Children's Place",
            "US Polo",
            "Flying Machine",
            "Crocs",
            "Puma",
            "Funskool",
            "Lego",
            "Luvlap",
            "Mamy Poko",
            "Mee Mee",
          ],
        },
      ],
    },
  },
  {
    id: crypto.randomUUID(),
    categoryItems: {
      title: "Home & Furniture",
      subItems: [
        {
          subtitle: "Kitchen, Cookware & Serveware",
          items: [
            "Pans",
            "Tawas",
            "Pressure Cookers",
            "Kitchen tools",
            "Gas Stoves",
            "Tableware & Dinnerware",
            "Coffee Mugs",
            "Dinner Set",
            "Barware",
            "Kitchen Storage",
            "Water Bottles",
            "Lunch Boxes",
            "Flasks",
            "Casseroles",
            "Kitchen Containers",
          ],
        },
        {
          subtitle: "Cleaning Supplies",
          items: ["Cleaning Supplies"],
        },
        {
          subtitle: "Furniture Top Offers",
          items: [
            "Bed Room Furniture",
            "Beds",
            "Mattresses",
            "Wardrobes",
            "Living Room Furniture",
            "Sofa",
            "Sofa Beds",
            "TV Units",
            "Dining Tables & Chairs",
            "Coffee Tables",
            "Shoe Racks",
            "Office & Study Furniture",
            "Kids Room Furniture",
            "DIY Furniture",
            "Bean Bags",
            "Collapsible Wardrobes",
          ],
        },
        {
          subtitle: "Furnishing",
          items: [
            "Bedsheets",
            "Curtains",
            "Cushions & Pillows",
            "Blankets",
            "Bath Towels",
            "Kitchen & Table Linen",
            "Floor Coverings",
          ],
        },
        {
          subtitle: "Smart Home Automation",
          items: ["Smart Security System", "Smart Door Locks"],
        },
        {
          subtitle: "Home Improvement",
          items: [
            "Tools & Measuring Equipments",
            "Home Utilities & Organizers",
            "Lawn & Gardening",
            "Bathroom & Kitchen Fittings",
          ],
        },
        {
          subtitle: "Home Decor",
          items: [
            "Paintings",
            "Clocks",
            "Wall Shelves",
            "Stickers",
            "Showpieces & Figurines",
          ],
        },
        {
          subtitle: "Home Lighting",
          items: [
            "Bulbs",
            "Wall Lamp",
            "Table Lamp",
            "Ceiling Lamp",
            "Emergency Lights",
          ],
        },
        {
          subtitle: "Festive Decor & Gifts",
          items: ["Festive Decor & Gifts"],
        },
        {
          subtitle: "Pet Supplies",
          items: ["Dogs", "Cats", "Fish & Aquatics"],
        },
        {
          subtitle: "Durability Certified Furniture",
          items: ["Durability Certified Furniture"],
        },
        {
          subtitle: "Featured",
          items: [
            "Christmas Store",
            "Mugs Store",
            "Gardening Store",
            "Stainless Steel Store",
            "Milton",
            "Bombay Dyeing",
            "@home",
            "HomeTown",
            "Ajanta",
            "Spaces by Welspun",
            "Prestige",
            "Perfect Home Store",
          ],
        },
      ],
    },
  },
  {
    id: crypto.randomUUID(),
    categoryItems: {
      title: "Sports, Books & More",
      subItems: [
        {
          subtitle: "Sports",
          items: [
            "Cricket",
            "Badminton",
            "Cycling",
            "Football",
            "Skating",
            "Camping & Hiking",
            "Swimming",
          ],
        },
        {
          subtitle: "Exercise & Fitness",
          items: [
            "Cardio Equipment",
            "Home Gyms",
            "Support",
            "Dumbbells",
            "Ab Exercisers",
            "Shakers & Sippers",
            "Yoga Mat",
            "Gym Gloves",
          ],
        },
        {
          subtitle: "Food Essentials",
          items: [
            "Nuts & Dry Fruits",
            "Tea, Coffee and Beverages",
            "Chocolates",
            "Snacks Corner",
            "Gifting Combos",
            "Sweets Store",
            "Jams, Spreads and Honey",
            "Breakfast Items",
          ],
        },
        {
          subtitle: "Health & Nutrition",
          items: [
            "All Supplements",
            "Protein Supplements",
            "Vitamin Supplements",
            "Health Drinks",
            "Ayurvedic Supplements",
          ],
        },
        {
          subtitle: "Books",
          items: [
            "Entrance Exams",
            "Academics",
            "Literature & Fiction",
            "Non Fiction",
            "Young Readers",
            "Self-Help",
            "E-Learning",
            "Preorders",
            "Indian Languages",
          ],
        },
        {
          subtitle: "Stationery",
          items: [
            "Pens",
            "Diaries",
            "Card Holders",
            "Desk Organizers",
            "Calculators",
            "Key Chains",
          ],
        },
        {
          subtitle: "Auto Accessories",
          items: [
            "Helmets & Riding Gears",
            "Car Audio/Video",
            "Car Mobile Accessories",
            "Car & Bike Care",
            "Vehicle Lubricants",
          ],
        },
        {
          subtitle: "Industrial & Scientific Tools",
          items: [
            "Industrial Measurement Devices",
            "Industrial Testing Devices",
            "Lab & Scientific Products",
            "Packaging & Shipping Products",
            "Safety Products",
          ],
        },
        {
          subtitle: "Medical Supplies",
          items: ["Pregnancy and Fertility Kits", "Hot Water Bag"],
        },
        {
          subtitle: "Music",
          items: ["Musical Instruments", "Music"],
        },
        {
          subtitle: "Movies & TV Shows",
          items: ["Movies & Tv shows"],
        },
        {
          subtitle: "Gaming",
          items: [
            "Gaming Consoles",
            "Gaming Accessories",
            "PS4 Games",
            "Smart Glasses (VR)",
          ],
        },
        {
          subtitle: "Grocery",
          items: ["Grocery (Only in Select Cities)"],
        },
      ],
    },
  },
  {
    id: crypto.randomUUID(),
    category: {
      title: "Flight",
      subItems: [],
    },
  },
  {
    id: crypto.randomUUID(),
    category: {
      title: "Offer Zone",
      subItems: [],
    },
  }
];
